# Generated by Django 4.0.6 on 2022-10-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donetasks', models.CharField(max_length=200)),
            ],
        ),
    ]
